# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4aa24720ec14b88ce3d31f07e330b8ee0753f25e2cb58c67073b7011092bb2ebafa62d2315191139af10dc7ebf9d44e698f91e181d13b55e15ed5ef94e432df3

test:
  secret_key_base: a64c8901bccfd68e1a08e3d361458ea9eb5cffb6a25dca24a35fabbdd1773bb287a9c06f648c9e429fd040753ef7a37beef8e52da97f843e201e87e3030b5335

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
